---
title: "cor_gpep_lineplot"
author: "Shiori"
date: "2026-02-02"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(tibble)
library(openxlsx)
library(ggplot2)
library(venndir)
library(ggbeeswarm)
library(clusterProfiler)
library(org.Mm.eg.db) 
library(ggpubr)
library(rstatix)
library(stats)
library(bio3d)
library(httr)
library(jsonlite)

source("G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/code/utils_cor_protein_lineplot.R")

```

```{r, fig.width=8, fig.height=5}

s_cor <- read.xlsx("G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/fig/CC_sps_cor_restrict.xlsx", 1)
igot_zscore<- read.xlsx("G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/result/sps_pattern_result.4.2_restrict.xlsx", "igot_zscore")
gpep_zscore<- read.xlsx("G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/result/sps_pattern_result.4.2_restrict.xlsx", "gpep_zscore")
output_dir<-"G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/fig/"
output_dir_fig<-"G:/Amed brain/glyco-decipher/240612_mouse_sps/analysis result 3 _MBR/zhang_final code/fig_temp/"

s_cor_GO<-GO_analysis(s_cor, "BP")
GO_plot(s_cor_GO, "BP")

write.xlsx(s_cor_GO, paste0(output_dir, "sps_cor_protein_BP_enrichment_res_restrict.xlsx"))
tar_ID<-"GO:0050808" #synapse organization
GO_res<-s_cor_GO

tar_GN<-extract_GN(s_cor_GO, tar_ID)

tar_igot_df<-igot_zscore%>%filter(GN %in% tar_GN, !is.na(igot_cluster))%>%select(GN, site_ID, igot_cluster,ends_with("igot"))
tar_gpep_df<-gpep_zscore%>%filter(GN %in% tar_GN, !is.na(gpep_cluster))%>%select(GN, site_ID, glycan_ID,acc_site_glycan_ID, gpep_cluster, ends_with("imp"))

igot_plot_df<-trans_longdata(tar_igot_df)%>%
              mutate(group_key = ifelse(igot_cluster == 1, "decre", "incre"),
                     pep_group_key = paste0(site_ID, "_", group_key)) 
gpep_plot_df<-trans_longdata_gpep_lineplot(tar_gpep_df)%>%
              mutate(pep_group_key = paste0(acc_site_glycan_ID, "_", group_key)) 

saveRDS(igot_plot_df, paste0(output_dir_fig, "sps_cor_synapseorg_igot_expattern.rds"))
saveRDS(gpep_plot_df, paste0(output_dir_fig, "sps_cor_synapseorg_gpep_expattern.rds"))

igot_cor_sps_org_line_plot<-expression_plot(igot_plot_df)
gpep_cor_sps_org_line_plot<-expression_plot(gpep_plot_df)

igot_cor_sps_org_line_plot
gpep_cor_sps_org_line_plot

saveRDS(igot_cor_sps_org_line_plot, paste0(output_dir_fig, "igot_cor_sps_org_line_plot.rds"))
saveRDS(gpep_cor_sps_org_line_plot, paste0(output_dir_fig, "gpep_cor_sps_org_line_plot.rds"))

```

